/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'philipp' at '6/21/16 11:39 AM' with Gradle 2.14
 *
 * @author philipp, @date 6/21/16 11:39 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
