/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'philipp' at '19.06.16 16:42' with Gradle 2.6
 *
 * @author philipp, @date 19.06.16 16:42
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
